export default {
    RECEIVE_RENTAL_SLIPS: "RECEIVE_RENTAL_SLIPS",
    ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
    UPDATE_ITEM_SUCCESS: "UPDATE_ITEM_SUCCESS",
    DELETE_ITEM_SUCCESS: "DELETE_ITEM_SUCCESS",

    // constants for select actions
    SELECT_RENTAL_MONTH: "SELECT_RENTAL_MONTH",
    SELECT_ITEM: "SELECT_ITEM"
}
